[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project]
name = "jupyverse"
description = "A set of FPS plugins implementing a Jupyter server"
keywords = ["jupyter", "server", "fastapi", "pluggy", "plugins"]
dynamic = ["version"]
requires-python = ">=3.7"
dependencies = [
    "fastapi>=0.82.0",
    "fps>=0.0.19",
    "fps-uvicorn>=0.0.19",
    "fps-auth-base>=0.0.42",
    "fps-contents>=0.0.42",
    "fps-kernels>=0.0.42",
    "fps-terminals>=0.0.42",
    "fps-nbconvert>=0.0.42",
    "fps-yjs>=0.0.42"
]

[[project.authors]]
name = "Jupyter Development Team"
email = "jupyter@googlegroups.com"

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.license]
text = "BSD 3-Clause License"

[project.urls]
Homepage = "https://jupyter.org"

[project.optional-dependencies]
jupyterlab = [ "fps-jupyterlab >=0.0.42",]
retrolab = [ "fps-retrolab >=0.0.42",]
auth = [ "fps-auth >=0.0.42",]
auth-fief = [ "fps-auth-fief >=0.0.42",]
noauth = ["fps-noauth >=0.0.42"]
test = [ "mypy", "types-setuptools", "pytest", "pytest-asyncio", "pytest-env", "requests", "websockets", "ipykernel",]
docs = [ "mkdocs", "mkdocs-material",]

[tool.hatch.envs.dev]
pre-install-commands = [
  "pip install -e ./plugins/auth_base",
  "pip install -e ./plugins/contents",
  "pip install -e ./plugins/frontend",
  "pip install -e ./plugins/frontend",
  "pip install -e ./plugins/kernels",
  "pip install -e ./plugins/lab",
  "pip install -e ./plugins/nbconvert",
  "pip install -e ./plugins/terminals",
  "pip install -e ./plugins/yjs",
]
dependencies = ["fastapi>=0.82.0"]
features = ["test"]

[tool.hatch.envs.dev.overrides]
matrix.auth.post-install-commands = [
  { value = "pip install -e ./plugins/auth_fief", if = ["auth_fief"] },
  { value = "pip install -e ./plugins/noauth", if = ["noauth"] },
  { value = "pip install -e ./plugins/auth", if = ["auth"] },
  { value = "pip install -e ./plugins/jupyterlab", if =["lab"]},
  { value = "pip install -e ./plugins/retrolab", if =["retro"]},
]

[[tool.hatch.envs.dev.matrix]]
frontend = ["lab", "retro"]
auth = ["noauth", "auth", "fief"]

[tool.hatch.envs.dev.scripts]
jupyverse = "fps_uvicorn.cli:app"

[tool.hatch.envs.docs]
features = ["docs"]

[tool.hatch.envs.docs.scripts]
build = "mkdocs build --clean --strict"
serve = "mkdocs serve --dev-addr localhost:8000"

[project.scripts]
jupyverse = "fps_uvicorn.cli:app"

[tool.check-manifest]
ignore = [ ".*",]

[tool.jupyter-releaser]
skip = [ "check-links", "check-manifest",]

[tool.flake8]
max-line-length = 100

[tool.jupyter-releaser.options]
python_packages = [
    "plugins/auth_base:fps-auth-base",
    "plugins/noauth:fps-noauth",
    "plugins/auth:fps-auth",
    "plugins/auth_fief:fps-auth-fief",
    "plugins/contents:fps-contents",
    "plugins/frontend:fps-frontend",
    "plugins/jupyterlab:fps-jupyterlab",
    "plugins/kernels:fps-kernels",
    "plugins/lab:fps-lab",
    "plugins/nbconvert:fps-nbconvert",
    "plugins/retrolab:fps-retrolab",
    "plugins/terminals:fps-terminals",
    "plugins/yjs:fps-yjs",
    "plugins/login:fps-login",
    ".:jupyverse:fps-auth-base,fps-noauth,fps-auth,fps-auth-fief,fps-contents,fps-jupyterlab,fps-kernels,fps-lab,fps-frontend,fps-nbconvert,fps-retrolab,fps-terminals,fps-yjs"
]

[tool.hatch.version]
path = "jupyverse/__init__.py"

[tool.pytest.ini_options]
asyncio_mode = "strict"
