name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest]
        python-version: [ '3.7', '3.8', '3.9', '3.10' ]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install jupyverse
      run: |
        python -m pip install ./plugins/auth_base
        python -m pip install ./plugins/frontend
        python -m pip install ./plugins/jupyterlab
        python -m pip install ./plugins/login
        python -m pip install ./plugins/auth
        python -m pip install ./plugins/contents
        python -m pip install ./plugins/kernels
        python -m pip install ./plugins/terminals
        python -m pip install ./plugins/lab
        python -m pip install ./plugins/nbconvert
        python -m pip install ./plugins/yjs
        python -m pip install .[test]

    - name: Check types
      run: |
        mypy jupyverse
        mypy plugins/auth_base/fps_auth_base
        mypy plugins/frontend/fps_frontend
        mypy plugins/contents/fps_contents
        mypy plugins/kernels/fps_kernels
        mypy plugins/retrolab/fps_retrolab
        mypy plugins/jupyterlab/fps_jupyterlab
        mypy plugins/lab/fps_lab
        mypy plugins/auth/fps_auth
        mypy plugins/nbconvert/fps_nbconvert
        mypy plugins/yjs/fps_yjs
        mypy plugins/terminals/fps_terminals
        mypy plugins/login/fps_login

    - name: Run tests
      run: |
        python3 -m pytest ./tests -v
