name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [ '3.7', '3.8', '3.9', '3.10' ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install jupyverse
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install ./plugins/auth_base
        python3 -m pip install ./plugins/frontend
        python3 -m pip install ./plugins/jupyterlab
        python3 -m pip install ./plugins/login
        python3 -m pip install ./plugins/auth
        python3 -m pip install ./plugins/contents
        python3 -m pip install ./plugins/kernels
        python3 -m pip install ./plugins/terminals
        python3 -m pip install ./plugins/lab
        python3 -m pip install ./plugins/nbconvert
        python3 -m pip install ./plugins/yjs
        python3 -m pip install .[test]

    - name: Check types
      run: |
        mypy jupyverse
        mypy plugins/auth_base/fps_auth_base
        mypy plugins/frontend/fps_frontend
        mypy plugins/contents/fps_contents
        mypy plugins/kernels/fps_kernels
        mypy plugins/retrolab/fps_retrolab
        mypy plugins/jupyterlab/fps_jupyterlab
        mypy plugins/lab/fps_lab
        mypy plugins/auth/fps_auth
        mypy plugins/nbconvert/fps_nbconvert
        mypy plugins/yjs/fps_yjs
        mypy plugins/terminals/fps_terminals
        mypy plugins/login/fps_login

    - name: Run tests
      run: |
        python3 -m pytest ./tests -v
